// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Goods is the golang structure for table goods.
type Goods struct {
	Id     uint64  `json:"id"     ` //
	Name   string  `json:"name"   ` //
	Type   string  `json:"type"   ` //
	Unit   string  `json:"unit"   ` //
	Price  float64 `json:"price"  ` //
	Tariff float64 `json:"tariff" ` //
}
